OPCODE_HANDSHAKE = 0
OPCODE_DOWNLOAD = 1
OPCODE_DATA = 2
OPCODE_ACK = 3
OPCODE_CLOSE = 7
OPCODE_ERROR = 4

HEADER_FORMAT = '!BIH'
PACKET_PAYLOAD_SIZE = 1400
SOCKET_RECV_BUFFER = 4096
ACK_BUFFER_SIZE = 1024

REQUEST_TIMEOUT = 0.2
HANDSHAKE_TIMEOUT = 2.0
TEARDOWN_TIMEOUT = 2.0
DATA_TRANSFER_TIMEOUT = 0.1
WORKER_SOCKET_TIMEOUT = 15.0
MAX_NETWORK_ATTEMPTS = 25
RECEIVE_TIMEOUT = 0.5
SW_RECEIVE_TIMEOUT = 1.0
SW_MAX_IDLE_TIMEOUTS = 15
SR_MAX_IDLE_TIMEOUTS = 30

MAX_RAM_BUFFER_PACKETS = 10000

# Teardown
TEARDOWN_ACK_RETRIES = 5
TEARDOWN_ACK_SLEEP = 0.05
TEARDOWN_GRACE_SECONDS = 0.5
CLIENT_TEARDOWN_TOTAL_ATTEMPTS = 15

CWMD_INITIAL = 10.0
CWMD_MAX = 500.0
CWMD_INCREMENT = 1.0
CWMD_BACKOFF = 0.5
CWMD_MIN = 30.0
SELECT_TIMEOUT = 0.005

MAX_FILE_SIZE = 20 * 1024 * 1024

SW_STRATEGY = 'sw'
SR_STRATEGY = 'sr'
